### ISSUE TITLE
有没有更方便的获取session的办法？

### ISSUE THREAD

**Issue by mofanx** [glovebx/moco-ai-client#1]
电脑端有一款ChatAll的应用，可以直接弹出Bing、Bard等的登录界面，登录后，自动获取并保存Session，不知道这款应用能不能实现类似的操作。

ChatAll网址：https://github.com/sunner/ChatALL/blob/main/README_ZH-CN.md

**Comment by glovebx** [comment]
技术上是没问题的，后续可以考虑

**Comment by mofanx** [comment]
期待更新👍

**Comment by glovebx** [comment]
暂时取消对bing和bard的支持
