### ISSUE TITLE
根据readme指引完全没找见session的获取方法

### ISSUE THREAD

**Issue by StrideLeo** [glovebx/moco-ai-client#2]

**Comment by glovebx** [comment]
Bing获取看这里：https://github.com/cssxsh/mirai-new-bing
其他获取session同理

**Comment by StrideLeo** [comment]
好的，搞定了Bard和bing。
readme中所说Poe，仅需m-b字符串，不需要api-key，这里的m-b字符是笔误吗？好像是p-b字符串

**Comment by glovebx** [comment]
> 好的，搞定了Bard和bing。 readme中所说Poe，仅需m-b字符串，不需要api-key，这里的m-b字符是笔误吗？好像是p-b字符串

m-b，登录quora.com能找到
